name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: apt-get update -qq
      - run: apt-get install -qq nasm g++-multilib gcc-multilib libc6-dev-i386 python3-pip python3-setuptools
      - run: python3 -m pip install meson==0.50.1 ninja
      - run: make gmp-bootstrap
      - run: make gtest-bootstrap
      - run: make gtest-bootstrap
      - run: meson builddir
      - run: ninja -C builddir -v



        